### ISSUE TITLE
Pulled

### ISSUE THREAD

**Issue by ghost** [google/nogotofail#132]
https://github.com/google/nogotofail/blob/eaa3fecf82ef1e5b0f21ab5c3f77f6a2dacc2805/nogotofail/clients/android/app/src/main/java/net/theFJ/AttacksPreferenceFragment.java

**Comment by jFJ13** [comment]
``

**Comment by ghost** [comment]
> https://github.com/google/nogotofail/blob/eaa3fecf82ef1e5b0f21ab5c3f77f6a2dacc2805/nogotofail/clients/android/app/src/main/java/net/theFJ/AttacksPreferenceFragment.java#L258

- [x]
