### ISSUE TITLE
Migration of Android Eclipse projects to Android Studio

### ISSUE THREAD

**Issue by mkenne11** [google/nogotofail#88]
I see Google is ending support for Eclipse ADT at the end of this year, and Android Studio will be the supported IDE:
http://android-developers.blogspot.com/2015/06/an-update-on-eclipse-android-developer.html

At some point the Android client and test-harness app projects should be migrated to Android Studio. I migrated the 2 app projects to Android Studio in the PII fork and am happy to kick off this task (and assign the issue to me) if you want.

See migrated projects in PII fork:
https://github.com/mkenne11/nogotofail-pii/tree/dev/nogotofail/clients/android
https://github.com/mkenne11/nogotofail-pii/tree/dev/nogotofail/test/android

**Comment by klyubin** [comment]
I suppose this has to happen at some point... Is there a way to avoid having tons of Gradle and IntelliJ IDEA files and JARs being added to the repository? I'm talking about ugliness such as gradle/wrapper and .idea directories.

**Comment by mkenne11** [comment]
I browsed suggestions for Android Studio project .gitignore file on stackoverflow - additional files that could be excluded from the PII forks I posted are *.iml files and most files under the /.idea folder.

I will experiment further before I submit a sample pull request for one of the migrated Eclipse projects.

**Comment by mkenne11** [comment]
I submitted PR #91 which migrates the ngtf Android client Eclipse project to Android Studio.

This was the minimum set of projects files I found for the project. I was able to discard the .idea and gradle/wrapper directories.

**Comment by mkenne11** [comment]
PR #91 was merged into the dev project branch.
